const SKYPICKER_BASE_API_URL = 'https://api.skypicker.com';

const LOCATION_TYPES = Object.freeze({
  AIRPORT: 'AIRPORT',
  AUTONOMOUS_TERRITORY: 'AUTONOMOUS_TERRITORY',
  CITY: 'CITY',
  COUNTRY: 'COUNTRY',
  STATION: 'STATION',
  SUBDIVISION: 'SUBDIVISION',
});

const LOCATION_RESULTS_SORT_TYPES = Object.freeze({
  ASCENDING_NAME: 'ASCENDING_NAME',
  ASCENDING_RANK: 'ASCENDING_RANK',
  DESCENDING_NAME: 'DESCENDING_NAME',
  DESCENDING_RANK: 'DESCENDING_RANK',
});

const FLIGHT_RESULTS_SORT_TYPES = Object.freeze({
  DATE: 'DATE',
  DURATION: 'DURATION',
  PRICE: 'PRICE',
  QUALITY: 'QUALITY',
});

const AIRLINES_FILTER_TYPE = Object.freeze({
  EXCLUDE: 'EXCLUDE',
  INCLUDE: 'INCLUDE',
});

export {
  SKYPICKER_BASE_API_URL,
  LOCATION_TYPES,
  LOCATION_RESULTS_SORT_TYPES,
  FLIGHT_RESULTS_SORT_TYPES,
  AIRLINES_FILTER_TYPE,
};
